apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: bookings-management
  name: bookings-management
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: bookings-management
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: bookings-management
    spec:
      containers:
        - image: bookings-management
          name: bookings-management
          ports:
            - containerPort: 8087
          resources: {}
      hostname: localhost
      restartPolicy: Always
status: {}
