apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: product-webapp
  name: product-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: product-webapp
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: product-webapp
    spec:
      containers:
        - image: product-webapp
          name: product-webapp
          ports:
            - containerPort: 4200
          resources: {}
      hostname: localhost
      restartPolicy: Always
status: {}
